{% set name = "django-autocomplete-light" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-autocomplete-light-{{ version }}.tar.gz
  sha256: 212576a17e3308ef7ca77e280b86684167916d2091d4b73640f38845d9516328

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.2
    - six

test:
  imports:
    - dal
    - dal_contenttypes
    - dal_genericm2m
    - dal_genericm2m_queryset_sequence
    - dal_gm2m
    - dal_gm2m_queryset_sequence
    - dal_legacy_static
    - dal_queryset_sequence
    - dal_select2
    - dal_select2_queryset_sequence
    - dal_select2_tagging
    - dal_select2_taggit
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-autocomplete-light.rtfd.org
  summary: Fresh autocompletes for Django
  dev_url: https://github.com/yourlabs/django-autocomplete-light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - maksdan
