{% set name = "django-autocomplete-light" %}
{% set version = "3.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 50f7b83681feec6491c38e6114d7a4fe80f9e99a8cc6c8458a3e7bb137ad6b1d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=3.2
    - six

test:
  imports:
    - dal
    - dal_contenttypes
    - dal_genericm2m
    - dal_genericm2m_queryset_sequence
    - dal_gm2m
    - dal_gm2m_queryset_sequence
    - dal_legacy_static
    - dal_queryset_sequence
    - dal_select2
    - dal_select2_queryset_sequence
    - dal_select2_tagging
    - dal_select2_taggit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://django-autocomplete-light.rtfd.org
  summary: Fresh autocompletes for Django
  dev_url: https://github.com/yourlabs/django-autocomplete-light
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - maksdan
