{% set name = "django-autocomplete-light" %}
{% set version = "3.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-autocomplete-light-{{ version }}.tar.gz
  sha256: 34e8af34a83622461d38f3a3824b622168ebe243b9889c982a7c7514b4110882

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7,<3|>=3.4,<4
  run:
    - python >=2.7,<3|>=3.4,<4
    - six

test:
  imports:
    - dal
    - dal.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-autocomplete-light.rtfd.org
  summary: Fresh autocompletes for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maksdan
