{% set name = "django-autocomplete-light" %}
{% set version = "3.9.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-autocomplete-light-{{ version }}.tar.gz
  sha256: 0f6da75c1c7186698b867a467a8cdb359f0513fdd8e09288a0c2fb018ae3d94e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7,<3|>=3.4,<4
  run:
    - python >=2.7,<3|>=3.4,<4
    - six

test:
  imports:
    - dal
    - dal.test
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://django-autocomplete-light.rtfd.org
  summary: Fresh autocompletes for Django
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maksdan
